ifq: eliminate /dev/stderr as that causes trouble.

diff --git a/bin/generic/ifq b/bin/generic/ifq
--- a/bin/generic/ifq
+++ b/bin/generic/ifq
@@ -19,7 +19,7 @@ usage() {
 
 # Utils
 error() {
-	echo "Error: $1" >/dev/stderr
+	echo "Error: $1" >&2
 	[ -z "$2" ] && usage 1
 	exit $2
 }
